### ISSUE TITLE
Bug report - crash with Quilt

### ISSUE THREAD

**Issue by ParodyVerse** [sisby-folk/picohud#1]
[crash-2023-06-25_18.02.23-client.txt](https://github.com/sisby-folk/picohud/files/11861399/crash-2023-06-25_18.02.23-client.txt)
Adding this mod to my mod list causes it to crash Minecraft whenever I click any button
PicoHUD 1.4.0
Quilt 0.19.1
Minecraft 1.19.4

**Comment by sleepingdragoninn** [comment]
Uhh this is a crash related to YetAnotherConfigLib (YACL) - can you confirm it occurs when only PicoHUD and YACL is installed, and doesn't occur when just YACL is installed? I have doubts this is related to PicoHUD considering it has 0 mixins.

`InjectionError: Critical injection failure: Redirector modifyChildrenCall(Lnet/minecraft/class_350;)Ljava/util/List; in #yet_another_config_lib:yacl.mixins.json`

**Comment by ParodyVerse** [comment]
Oh removing YACL fixed it! Thanks! I also had this issue with HT's Treechop and Coordinates display as well, so thanks!
